### ISSUE TITLE
Email attachments include file path

### ISSUE THREAD

**Issue by falconraptor** [falconraptor/LiteSpeed#19]
https://github.com/falconraptor/LiteSpeed/blob/68a209b4f58c5f50e49303456a5f75dbbc73dec0/litespeed/mail.py#L75
Should wrap `f` in `os.path.basename`

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project and can u assign me this issue:)

**Comment by Vinayaka2k** [comment]
Hello, @Krish-bhardwaj  please assign this issue to me if you're not working on this. Thanks

**Comment by falconraptor** [comment]
Fixed in #20
