### ISSUE TITLE
BUG: Serve returning application/octet-stream instead of text/css

### ISSUE THREAD

**Issue by ModernMAK** [falconraptor/LiteSpeed#4]
When serving a css file, headers are set to 'application/octet-stream' instead of the expected 'text/css'

**Comment by falconraptor** [comment]
@ModernMAK I am not seeing any problems. It is working fine for me. Please check the end of the examples.py file to see how I serve those files. If you are doing it any other way let me know.

**Comment by ModernMAK** [comment]
Using 'no_end_slash = True' solves the issue

An example for anyone running into this: 
`@route("css/(.*)", no_end_slash=True)`
