### ISSUE TITLE
register_error_route hidden inside App

### ISSUE THREAD

**Issue by ModernMAK** [falconraptor/LiteSpeed#5]
register_error_route is hidden inside App, where as route is not. 

Id like it to be exposed inside litespeed for consistency.

**Comment by ModernMAK** [comment]
Somewhat unrelated, but it is about consistency. `function` in register_error_route should be renamed to `f` to mach route's definition.

**Comment by falconraptor** [comment]
Now you can do
@register_error_page(code=500)
 or 
register_error_page(function, 500)
